import type { CopilotContext, CopilotProvider, CopilotResponse } from './copilotTypes';
import { DeterministicCopilotProvider } from './deterministicCopilot';

export const AERIS_SYSTEM_PROMPT = `You are AERIS, an environmental intelligence assistant for Delhi NCR.
Use only the supplied context. Never invent measurements, forecasts, weather,
causes, confidence scores, AQI values, or intervention outcomes.
Do not turn correlation into causation. Treat interventions as sensitivity
estimates, not causal predictions. Distinguish REANALYSIS, PREDICTED,
ESTIMATED, and AI-GENERATED information. Return valid JSON.`.trim();

export class BedrockCopilotProvider implements CopilotProvider {
readonly id = 'BEDROCK' as const;
private readonly fallback = new DeterministicCopilotProvider();

async isAvailable(): Promise<boolean> {
return typeof window !== 'undefined';
}

async generate(context: CopilotContext): Promise<CopilotResponse> {
try {
const response = await fetch('/api/copilot', {
method: 'POST',
headers: { 'Content-Type': 'application/json' },
body: JSON.stringify({ context }),
});

  if (!response.ok) {
    throw new Error('Copilot API returned HTTP ' + response.status);
  }

  const result = await response.json() as CopilotResponse;

  if (
    result.generatedBy !== 'BEDROCK' ||
    !result.what?.summary ||
    !result.why?.summary ||
    !result.next?.summary ||
    !result.action?.summary
  ) {
    throw new Error('Invalid Bedrock response');
  }

  return result;
} catch (error) {
  console.error('[AERIS] Bedrock unavailable; using deterministic fallback.', error);
  const result = await this.fallback.generate(context);
  return {
    ...result,
    generatedBy: 'DETERMINISTIC',
    disclaimers: [
      'Bedrock API unavailable; this response was generated by the deterministic fallback.',
      ...result.disclaimers,
    ],
  };
}

}
}
