/**
 * AERIS Copilot Service
 *
 * The application-facing entry point for the Copilot.
 * Handles provider selection, context construction, and error handling.
 *
 * Provider priority:
 *   1. BedrockCopilotProvider (if VITE_BEDROCK_MODEL_ID is set and available)
 *   2. DeterministicCopilotProvider (always available — guaranteed fallback)
 *
 * Usage:
 *   const result = await generateCopilotResponse(telemetry, forecast, history, anomalies, dataMode, scenario);
 */

import type { StationTelemetry } from '@/types/telemetry';
import type { StationForecast } from '@/types/forecast';
import type { AnomalyRecord } from '@/services/anomalyService';
import type { HistoricalPoint } from '@/services/historicalService';
import type { ScenarioImpact } from '@/types/intervention';
import type { CopilotProvider, CopilotResponse } from './copilotTypes';
import type { DataMode } from '@/types/telemetry';
import { buildCopilotContext } from './contextBuilder';
import { DeterministicCopilotProvider } from './deterministicCopilot';
import { BedrockCopilotProvider } from './bedrockAdapter';

// ─── Provider Registry ────────────────────────────────────────────────────────

const PROVIDERS: CopilotProvider[] = [
  new BedrockCopilotProvider(),
  new DeterministicCopilotProvider(),
];

/**
 * Selects the first available provider from the registry.
 * Deterministic provider is always last and always available.
 */
async function selectProvider(): Promise<CopilotProvider> {
  for (const provider of PROVIDERS) {
    if (await provider.isAvailable()) {
      return provider;
    }
  }
  // Guaranteed: DeterministicCopilotProvider is last and always returns true
  return new DeterministicCopilotProvider();
}

/**
 * Generates a CopilotResponse from the current AERIS state.
 *
 * Error handling: if the selected provider throws, we fall back to the
 * deterministic provider to ensure the Copilot never returns a broken state.
 */
export async function generateCopilotResponse(
  telemetry: StationTelemetry,
  forecast: StationForecast,
  historical: HistoricalPoint[],
  anomalies: AnomalyRecord[],
  dataMode: DataMode,
  scenario: ScenarioImpact | null = null
): Promise<CopilotResponse> {
  const context = buildCopilotContext(
    telemetry,
    forecast,
    historical,
    anomalies,
    dataMode,
    scenario
  );

  const provider = await selectProvider();

  try {
    return await provider.generate(context);
  } catch (err) {
    // Transparent error recovery — always fall back to deterministic
    console.error(`[AERIS Copilot] Provider ${provider.id} failed, falling back to deterministic:`, err);
    const fallback = new DeterministicCopilotProvider();
    const result = await fallback.generate(context);
    return {
      ...result,
      disclaimers: [
        `Copilot provider error — this response was generated by the deterministic fallback. Error: ${err instanceof Error ? err.message : 'Unknown error'}`,
        ...result.disclaimers,
      ],
    };
  }
}

// Re-export types for convenience
export type { CopilotResponse, CopilotContext, CopilotAudience } from './copilotTypes';
