/**
 * DataProvenance: the strictly-enforced data provenance categories for AERIS.
 *
 * Every data value surfaced in the UI or stored in the database MUST carry one of
 * these categories so users always know the origin of what they are looking at.
 *
 * - MEASURED      : Direct observation from an actual monitoring / ground IoT station.
 * - REANALYSIS    : Historical / reanalysis / gridded / atmospheric model-derived data (e.g. Open-Meteo CAMS/ECMWF).
 * - SIMULATED     : Deterministic/seeded demo data generated offline. Never call demo data MEASURED.
 * - PREDICTED     : Output from an evaluated ML forecasting model.
 * - ESTIMATED     : Output from the Intervention Scenario Sensitivity model (non-causal scenario).
 * - AI_GENERATED  : Diagnostic brief or advisory generated by an LLM (Amazon Bedrock).
 */
export type DataProvenance =
  | 'MEASURED'
  | 'REANALYSIS'
  | 'SIMULATED'
  | 'PREDICTED'
  | 'ESTIMATED'
  | 'AI_GENERATED';
