import type { DataProvenance } from '@/types';

interface ProvenanceBadgeProps {
  provenance: DataProvenance;
  /** If true, renders a compact version for tight spaces. */
  compact?: boolean;
}

const PROVENANCE_CONFIG: Record<
  DataProvenance,
  { label: string; cssClass: string; title: string }
> = {
  MEASURED: {
    label: 'Measured',
    cssClass: 'prov-badge--measured',
    title: 'Direct observation from an actual monitoring / ground station.',
  },
  REANALYSIS: {
    label: 'Reanalysis',
    cssClass: 'prov-badge--reanalysis',
    title: 'Atmospheric reanalysis / gridded model data (Open-Meteo CAMS/ECMWF).',
  },
  SIMULATED: {
    label: 'Simulated',
    cssClass: 'prov-badge--simulated',
    title: 'Deterministic demo data generated offline — not a real measurement.',
  },
  PREDICTED: {
    label: 'Predicted',
    cssClass: 'prov-badge--predicted',
    title: 'Output from an evaluated ML forecasting model.',
  },
  ESTIMATED: {
    label: 'Estimated',
    cssClass: 'prov-badge--estimated',
    title: 'Scenario sensitivity model output — not a causal prediction.',
  },
  AI_GENERATED: {
    label: 'AI-Generated',
    cssClass: 'prov-badge--ai-generated',
    title: 'Diagnostic brief generated by an LLM (Amazon Bedrock).',
  },
};

/**
 * ProvenanceBadge
 *
 * Renders an explicit, colour-coded badge indicating the data origin of any
 * AERIS data value. MUST be displayed alongside every data value shown in the UI.
 * This badge is the user's primary trust signal.
 */
export function ProvenanceBadge({ provenance, compact = false }: ProvenanceBadgeProps) {
  const config = PROVENANCE_CONFIG[provenance];
  return (
    <span
      className={`prov-badge ${config.cssClass}`}
      title={config.title}
      aria-label={`Data provenance: ${config.label}`}
    >
      {compact ? provenance.charAt(0) : config.label}
    </span>
  );
}
